### Reading record.json file

In [10]:
fd = open("record.json","r")
txt = fd.read()
fd.close()

### Printing the txt file

In [11]:
txt

'{"11602260": {"Name": "LOUIS VUITTON", "Mft. Date": "23-01-2021", "Qty": 9910, "Price": 250, "Discount": 50}, "11602261": {"Name": "GUCCI", "Mft. Date": "25-01-2021", "Qty": 9500, "Price": 240, "Discount": 45}, "11602262": {"Name": "VERSACE", "Mft. Date": "27-01-2021", "Qty": 9000, "Price": 230, "Discount": 40}, "11602263": {"Name": "PRADA", "Mft. Date": "29-01-2021", "Qty": 8500, "Price": 220, "Discount": 35}, "11602264": {"Name": "GIVENCHI", "Mft. Date": "31-01-2021", "Qty": 8000, "Price": 210, "Discount": 30}, "11602265": {"Name": "ARMANI", "Mft. Date": "03-02-2021", "Qty": 7500, "Price": 200, "Discount": 25}, "11602266": {"Name": "FENDI", "Mft. Date": "05-02-2021", "Qty": 7000, "Price": 190, "Discount": 20}, "11602267": {"Name": "CHANEL", "Mft. Date": "07-02-2021", "Qty": 6500, "Price": 180, "Discount": 15}, "11602268": {"Name": "RALPH LAUREN", "Mft. Date": "09-02-2021", "Qty": 6000, "Price": 170, "Discount": 10}, "11602269": {"Name": "HUGO BOSS", "Mft. Date": "11-02-2021", "Qty": 5500, "Price": 160, "Discount": 50}, "11602270": {"Name": "HERMES", "Mft. Date": "13-02-2021", "Qty": 5000, "Price": 160, "Discount": 45}, "11602271": {"Name": "YVES SAINT LAURENT", "Mft. Date": "15-02-2021", "Qty": 4500, "Price": 160, "Discount": 40}, "11602272": {"Name": "DIOR", "Mft. Date": "17-02-2021", "Qty": 4000, "Price": 150, "Discount": 35}, "11602273": {"Name": "VALENTINO", "Mft. Date": "19-02-2021", "Qty": 3500, "Price": 140, "Discount": 30}, "11602274": {"Name": "SALVATORE FERRAGAMO", "Mft. Date": "21-02-2021", "Qty": 3000, "Price": 130, "Discount": 25}, "11602275": {"Name": "DOLCE & GABBANA", "Mft. Date": "23-02-2021", "Qty": 2500, "Price": 120, "Discount": 20}, "11602276": {"Name": "MARC JACOBS", "Mft. Date": "25-02-2021", "Qty": 2000, "Price": 110, "Discount": 15}, "11602277": {"Name": "GUESS", "Mft. Date": "27-02-2021", "Qty": 1500, "Price": 100, "Discount": 10}, "11602278": {"Name": "ABERCROMBIE & FITCH", "Mft. Date": "29-02-2021", "Qty": 1000, "Price": 90, "Discount": 50}, "11602279": {"Name": "TED BAKER", "Mft. Date": "31-02-2021", "Qty": 900, "Price": 80, "Discount": 45}, "11602280": {"Name": "CHRISTIAN LOUBOUTIN", "Mft. Date": "3-03-2021", "Qty": 800, "Price": 70, "Discount": 40}, "11602281": {"Name": "CHLOE", "Mft. Date": "05-03-2021", "Qty": 700, "Price": 60, "Discount": 35}, "11602282": {"Name": "ALEXANDER MCQUEEN", "Mft. Date": "07-03-2021", "Qty": 600, "Price": 50, "Discount": 30}, "11602283": {"Name": "BURBERRY", "Mft. Date": "09-03-2021", "Qty": 500, "Price": 40, "Discount": 25}, "11602284": {"Name": "COACH", "Mft. Date": "11-03-2021", "Qty": 400, "Price": 30, "Discount": 20}, "11602285": {"Name": "COBB", "Mft. Date": "13-03-2021", "Qty": 300, "Price": 20, "Discount": 15}, "11602286": {"Name": "LOUIS PHILLIPE", "Mft. Date": "15-03-2021", "Qty": 200, "Price": 18, "Discount": 10}, "11602287": {"Name": "ALLEN SOLLY", "Mft. Date": "17-03-2021", "Qty": 190, "Price": 16, "Discount": 50}, "11602288": {"Name": "NIKE", "Mft. Date": "19-03-2021", "Qty": 180, "Price": 15, "Discount": 45}, "11602289": {"Name": "ADIDAS", "Mft. Date": "21-03-2021", "Qty": 100, "Price": 10, "Discount": 40}}'

### Importing json library and converting into a dictionary

In [12]:
import json
record  = json.loads(txt)
record

{'11602260': {'Name': 'LOUIS VUITTON',
  'Mft. Date': '23-01-2021',
  'Qty': 9910,
  'Price': 250,
  'Discount': 50},
 '11602261': {'Name': 'GUCCI',
  'Mft. Date': '25-01-2021',
  'Qty': 9500,
  'Price': 240,
  'Discount': 45},
 '11602262': {'Name': 'VERSACE',
  'Mft. Date': '27-01-2021',
  'Qty': 9000,
  'Price': 230,
  'Discount': 40},
 '11602263': {'Name': 'PRADA',
  'Mft. Date': '29-01-2021',
  'Qty': 8500,
  'Price': 220,
  'Discount': 35},
 '11602264': {'Name': 'GIVENCHI',
  'Mft. Date': '31-01-2021',
  'Qty': 8000,
  'Price': 210,
  'Discount': 30},
 '11602265': {'Name': 'ARMANI',
  'Mft. Date': '03-02-2021',
  'Qty': 7500,
  'Price': 200,
  'Discount': 25},
 '11602266': {'Name': 'FENDI',
  'Mft. Date': '05-02-2021',
  'Qty': 7000,
  'Price': 190,
  'Discount': 20},
 '11602267': {'Name': 'CHANEL',
  'Mft. Date': '07-02-2021',
  'Qty': 6500,
  'Price': 180,
  'Discount': 15},
 '11602268': {'Name': 'RALPH LAUREN',
  'Mft. Date': '09-02-2021',
  'Qty': 6000,
  'Price': 170,
  'Discount': 10},
 '11602269': {'Name': 'HUGO BOSS',
  'Mft. Date': '11-02-2021',
  'Qty': 5500,
  'Price': 160,
  'Discount': 50},
 '11602270': {'Name': 'HERMES',
  'Mft. Date': '13-02-2021',
  'Qty': 5000,
  'Price': 160,
  'Discount': 45},
 '11602271': {'Name': 'YVES SAINT LAURENT',
  'Mft. Date': '15-02-2021',
  'Qty': 4500,
  'Price': 160,
  'Discount': 40},
 '11602272': {'Name': 'DIOR',
  'Mft. Date': '17-02-2021',
  'Qty': 4000,
  'Price': 150,
  'Discount': 35},
 '11602273': {'Name': 'VALENTINO',
  'Mft. Date': '19-02-2021',
  'Qty': 3500,
  'Price': 140,
  'Discount': 30},
 '11602274': {'Name': 'SALVATORE FERRAGAMO',
  'Mft. Date': '21-02-2021',
  'Qty': 3000,
  'Price': 130,
  'Discount': 25},
 '11602275': {'Name': 'DOLCE & GABBANA',
  'Mft. Date': '23-02-2021',
  'Qty': 2500,
  'Price': 120,
  'Discount': 20},
 '11602276': {'Name': 'MARC JACOBS',
  'Mft. Date': '25-02-2021',
  'Qty': 2000,
  'Price': 110,
  'Discount': 15},
 '11602277': {'Name': 'GUESS',
  'Mft. Date': '27-02-2021',
  'Qty': 1500,
  'Price': 100,
  'Discount': 10},
 '11602278': {'Name': 'ABERCROMBIE & FITCH',
  'Mft. Date': '29-02-2021',
  'Qty': 1000,
  'Price': 90,
  'Discount': 50},
 '11602279': {'Name': 'TED BAKER',
  'Mft. Date': '31-02-2021',
  'Qty': 900,
  'Price': 80,
  'Discount': 45},
 '11602280': {'Name': 'CHRISTIAN LOUBOUTIN',
  'Mft. Date': '3-03-2021',
  'Qty': 800,
  'Price': 70,
  'Discount': 40},
 '11602281': {'Name': 'CHLOE',
  'Mft. Date': '05-03-2021',
  'Qty': 700,
  'Price': 60,
  'Discount': 35},
 '11602282': {'Name': 'ALEXANDER MCQUEEN',
  'Mft. Date': '07-03-2021',
  'Qty': 600,
  'Price': 50,
  'Discount': 30},
 '11602283': {'Name': 'BURBERRY',
  'Mft. Date': '09-03-2021',
  'Qty': 500,
  'Price': 40,
  'Discount': 25},
 '11602284': {'Name': 'COACH',
  'Mft. Date': '11-03-2021',
  'Qty': 400,
  'Price': 30,
  'Discount': 20},
 '11602285': {'Name': 'COBB',
  'Mft. Date': '13-03-2021',
  'Qty': 300,
  'Price': 20,
  'Discount': 15},
 '11602286': {'Name': 'LOUIS PHILLIPE',
  'Mft. Date': '15-03-2021',
  'Qty': 200,
  'Price': 18,
  'Discount': 10},
 '11602287': {'Name': 'ALLEN SOLLY',
  'Mft. Date': '17-03-2021',
  'Qty': 190,
  'Price': 16,
  'Discount': 50},
 '11602288': {'Name': 'NIKE',
  'Mft. Date': '19-03-2021',
  'Qty': 180,
  'Price': 15,
  'Discount': 45},
 '11602289': {'Name': 'ADIDAS',
  'Mft. Date': '21-03-2021',
  'Qty': 100,
  'Price': 10,
  'Discount': 40}}

### Giving the details to the new item to be added to inventory

In [19]:
prod_id = input("Enter the id : ")
name = input("Enter the name of the product : ")
mft_date = input("Enter the manufacturing date :")
qty = int(input("Enter the quantity :"))
price = int(input("Enter the price : "))
discount = int(input("Enter the discount : "))

Enter the id : 11602291
Enter the name of the product : ZARA
Enter the manufacturing date :25-03-2021
Enter the quantity :80
Enter the price : 270
Enter the discount : 30

### Adding new item to the inventory

In [20]:
record[prod_id] = {'Name': name , 'Mft. Date': mft_date , 'Qty': qty ,  'Price' : price , 'Discount': discount}

### Printing the record with the new item added

In [21]:
record

{'11602260': {'Name': 'LOUIS VUITTON',
  'Mft. Date': '23-01-2021',
  'Qty': 10000,
  'Price': 250,
  'Discount': 50},
 '11602261': {'Name': 'GUCCI',
  'Mft. Date': '25-01-2021',
  'Qty': 9500,
  'Price': 240,
  'Discount': 45},
 '11602262': {'Name': 'VERSACE',
  'Mft. Date': '27-01-2021',
  'Qty': 9000,
  'Price': 230,
  'Discount': 40},
 '11602263': {'Name': 'PRADA',
  'Mft. Date': '29-01-2021',
  'Qty': 8500,
  'Price': 220,
  'Discount': 35},
 '11602264': {'Name': 'GIVENCHI',
  'Mft. Date': '31-01-2021',
  'Qty': 8000,
  'Price': 210,
  'Discount': 30},
 '11602265': {'Name': 'ARMANI',
  'Mft. Date': '03-02-2021',
  'Qty': 7500,
  'Price': 200,
  'Discount': 25},
 '11602266': {'Name': 'FENDI',
  'Mft. Date': '05-02-2021',
  'Qty': 7000,
  'Price': 190,
  'Discount': 20},
 '11602267': {'Name': 'CHANEL',
  'Mft. Date': '07-02-2021',
  'Qty': 6500,
  'Price': 180,
  'Discount': 15},
 '11602268': {'Name': 'RALPH LAUREN',
  'Mft. Date': '09-02-2021',
  'Qty': 6000,
  'Price': 170,
  'Discount': 10},
 '11602269': {'Name': 'HUGO BOSS',
  'Mft. Date': '11-02-2021',
  'Qty': 5500,
  'Price': 160,
  'Discount': 50},
 '11602270': {'Name': 'HERMES',
  'Mft. Date': '13-02-2021',
  'Qty': 5000,
  'Price': 160,
  'Discount': 45},
 '11602271': {'Name': 'YVES SAINT LAURENT',
  'Mft. Date': '15-02-2021',
  'Qty': 4500,
  'Price': 160,
  'Discount': 40},
 '11602272': {'Name': 'DIOR',
  'Mft. Date': '17-02-2021',
  'Qty': 4000,
  'Price': 150,
  'Discount': 35},
 '11602273': {'Name': 'VALENTINO',
  'Mft. Date': '19-02-2021',
  'Qty': 3500,
  'Price': 140,
  'Discount': 30},
 '11602274': {'Name': 'SALVATORE FERRAGAMO',
  'Mft. Date': '21-02-2021',
  'Qty': 3000,
  'Price': 130,
  'Discount': 25},
 '11602275': {'Name': 'DOLCE & GABBANA',
  'Mft. Date': '23-02-2021',
  'Qty': 2500,
  'Price': 120,
  'Discount': 20},
 '11602276': {'Name': 'MARC JACOBS',
  'Mft. Date': '25-02-2021',
  'Qty': 2000,
  'Price': 110,
  'Discount': 15},
 '11602277': {'Name': 'GUESS',
  'Mft. Date': '27-02-2021',
  'Qty': 1500,
  'Price': 100,
  'Discount': 10},
 '11602278': {'Name': 'ABERCROMBIE & FITCH',
  'Mft. Date': '29-02-2021',
  'Qty': 1000,
  'Price': 90,
  'Discount': 50},
 '11602279': {'Name': 'TED BAKER',
  'Mft. Date': '31-02-2021',
  'Qty': 900,
  'Price': 80,
  'Discount': 45},
 '11602280': {'Name': 'CHRISTIAN LOUBOUTIN',
  'Mft. Date': '3-03-2021',
  'Qty': 800,
  'Price': 70,
  'Discount': 40},
 '11602281': {'Name': 'CHLOE',
  'Mft. Date': '05-03-2021',
  'Qty': 700,
  'Price': 60,
  'Discount': 35},
 '11602282': {'Name': 'ALEXANDER MCQUEEN',
  'Mft. Date': '07-03-2021',
  'Qty': 600,
  'Price': 50,
  'Discount': 30},
 '11602283': {'Name': 'BURBERRY',
  'Mft. Date': '09-03-2021',
  'Qty': 500,
  'Price': 40,
  'Discount': 25},
 '11602284': {'Name': 'COACH',
  'Mft. Date': '11-03-2021',
  'Qty': 400,
  'Price': 30,
  'Discount': 20},
 '11602285': {'Name': 'COBB',
  'Mft. Date': '13-03-2021',
  'Qty': 300,
  'Price': 20,
  'Discount': 15},
 '11602286': {'Name': 'LOUIS PHILLIPE',
  'Mft. Date': '15-03-2021',
  'Qty': 200,
  'Price': 18,
  'Discount': 10},
 '11602287': {'Name': 'ALLEN SOLLY',
  'Mft. Date': '17-03-2021',
  'Qty': 190,
  'Price': 16,
  'Discount': 50},
 '11602288': {'Name': 'NIKE',
  'Mft. Date': '19-03-2021',
  'Qty': 180,
  'Price': 15,
  'Discount': 45},
 '11602289': {'Name': 'ADIDAS',
  'Mft. Date': '21-03-2021',
  'Qty': 100,
  'Price': 10,
  'Discount': 40},
 '11602290': {'Name': 'LEVIS',
  'Mft. Date': '23-03-2021',
  'Qty': 90,
  'Price': 280,
  'Discount': 35},
 '11602291': {'Name': 'ZARA',
  'Mft. Date': '25-03-2021',
  'Qty': 80,
  'Price': 270,
  'Discount': 30}}

### Checking if the qty of a given is  same as that of the qty being given as an input

In [16]:
id = input("Enter the id : ")
qty = int(input("Enter the qty : "))
for id in record:
    if qty != record[id]['Qty']:
        new_qty = record[id]['Qty'] + qty
        break
    else:
        new_qty = record[id]['Qty']
        break

Enter the id : 11602260
Enter the qty : 90

### Updating the record with the new qty value to the item

In [17]:
record[id]['Qty'] = new_qty

### Printing the record with the new value of qty for the item

In [18]:
record

{'11602260': {'Name': 'LOUIS VUITTON',
  'Mft. Date': '23-01-2021',
  'Qty': 10000,
  'Price': 250,
  'Discount': 50},
 '11602261': {'Name': 'GUCCI',
  'Mft. Date': '25-01-2021',
  'Qty': 9500,
  'Price': 240,
  'Discount': 45},
 '11602262': {'Name': 'VERSACE',
  'Mft. Date': '27-01-2021',
  'Qty': 9000,
  'Price': 230,
  'Discount': 40},
 '11602263': {'Name': 'PRADA',
  'Mft. Date': '29-01-2021',
  'Qty': 8500,
  'Price': 220,
  'Discount': 35},
 '11602264': {'Name': 'GIVENCHI',
  'Mft. Date': '31-01-2021',
  'Qty': 8000,
  'Price': 210,
  'Discount': 30},
 '11602265': {'Name': 'ARMANI',
  'Mft. Date': '03-02-2021',
  'Qty': 7500,
  'Price': 200,
  'Discount': 25},
 '11602266': {'Name': 'FENDI',
  'Mft. Date': '05-02-2021',
  'Qty': 7000,
  'Price': 190,
  'Discount': 20},
 '11602267': {'Name': 'CHANEL',
  'Mft. Date': '07-02-2021',
  'Qty': 6500,
  'Price': 180,
  'Discount': 15},
 '11602268': {'Name': 'RALPH LAUREN',
  'Mft. Date': '09-02-2021',
  'Qty': 6000,
  'Price': 170,
  'Discount': 10},
 '11602269': {'Name': 'HUGO BOSS',
  'Mft. Date': '11-02-2021',
  'Qty': 5500,
  'Price': 160,
  'Discount': 50},
 '11602270': {'Name': 'HERMES',
  'Mft. Date': '13-02-2021',
  'Qty': 5000,
  'Price': 160,
  'Discount': 45},
 '11602271': {'Name': 'YVES SAINT LAURENT',
  'Mft. Date': '15-02-2021',
  'Qty': 4500,
  'Price': 160,
  'Discount': 40},
 '11602272': {'Name': 'DIOR',
  'Mft. Date': '17-02-2021',
  'Qty': 4000,
  'Price': 150,
  'Discount': 35},
 '11602273': {'Name': 'VALENTINO',
  'Mft. Date': '19-02-2021',
  'Qty': 3500,
  'Price': 140,
  'Discount': 30},
 '11602274': {'Name': 'SALVATORE FERRAGAMO',
  'Mft. Date': '21-02-2021',
  'Qty': 3000,
  'Price': 130,
  'Discount': 25},
 '11602275': {'Name': 'DOLCE & GABBANA',
  'Mft. Date': '23-02-2021',
  'Qty': 2500,
  'Price': 120,
  'Discount': 20},
 '11602276': {'Name': 'MARC JACOBS',
  'Mft. Date': '25-02-2021',
  'Qty': 2000,
  'Price': 110,
  'Discount': 15},
 '11602277': {'Name': 'GUESS',
  'Mft. Date': '27-02-2021',
  'Qty': 1500,
  'Price': 100,
  'Discount': 10},
 '11602278': {'Name': 'ABERCROMBIE & FITCH',
  'Mft. Date': '29-02-2021',
  'Qty': 1000,
  'Price': 90,
  'Discount': 50},
 '11602279': {'Name': 'TED BAKER',
  'Mft. Date': '31-02-2021',
  'Qty': 900,
  'Price': 80,
  'Discount': 45},
 '11602280': {'Name': 'CHRISTIAN LOUBOUTIN',
  'Mft. Date': '3-03-2021',
  'Qty': 800,
  'Price': 70,
  'Discount': 40},
 '11602281': {'Name': 'CHLOE',
  'Mft. Date': '05-03-2021',
  'Qty': 700,
  'Price': 60,
  'Discount': 35},
 '11602282': {'Name': 'ALEXANDER MCQUEEN',
  'Mft. Date': '07-03-2021',
  'Qty': 600,
  'Price': 50,
  'Discount': 30},
 '11602283': {'Name': 'BURBERRY',
  'Mft. Date': '09-03-2021',
  'Qty': 500,
  'Price': 40,
  'Discount': 25},
 '11602284': {'Name': 'COACH',
  'Mft. Date': '11-03-2021',
  'Qty': 400,
  'Price': 30,
  'Discount': 20},
 '11602285': {'Name': 'COBB',
  'Mft. Date': '13-03-2021',
  'Qty': 300,
  'Price': 20,
  'Discount': 15},
 '11602286': {'Name': 'LOUIS PHILLIPE',
  'Mft. Date': '15-03-2021',
  'Qty': 200,
  'Price': 18,
  'Discount': 10},
 '11602287': {'Name': 'ALLEN SOLLY',
  'Mft. Date': '17-03-2021',
  'Qty': 190,
  'Price': 16,
  'Discount': 50},
 '11602288': {'Name': 'NIKE',
  'Mft. Date': '19-03-2021',
  'Qty': 180,
  'Price': 15,
  'Discount': 45},
 '11602289': {'Name': 'ADIDAS',
  'Mft. Date': '21-03-2021',
  'Qty': 100,
  'Price': 10,
  'Discount': 40},
 '11602290': {'Name': 'LEVIS',
  'Mft. Date': '23-03-2021',
  'Qty': 90,
  'Price': 280,
  'Discount': 35}}

### Checking if the price given as input  is same as that of item price in the dictionary

In [25]:
id = input("Enter the id :")
price = int(input("Enter the price : "))
if id in record:
    if price != record[id]['Price']:
        new_price = record[id]['Price'] + price
    else:
        new_price = record[id]['Price']
else:
    print("Invalid Input")

Enter the id :11602260
Enter the price : 10

### Updating the price in the dictionary

In [26]:
record[id]['Price'] = new_price

### Printing the dictionary with updated price

In [27]:
record

{'11602260': {'Name': 'LOUIS VUITTON',
  'Mft. Date': '23-01-2021',
  'Qty': 10000,
  'Price': 260,
  'Discount': 50},
 '11602261': {'Name': 'GUCCI',
  'Mft. Date': '25-01-2021',
  'Qty': 9500,
  'Price': 240,
  'Discount': 45},
 '11602262': {'Name': 'VERSACE',
  'Mft. Date': '27-01-2021',
  'Qty': 9000,
  'Price': 230,
  'Discount': 40},
 '11602263': {'Name': 'PRADA',
  'Mft. Date': '29-01-2021',
  'Qty': 8500,
  'Price': 220,
  'Discount': 35},
 '11602264': {'Name': 'GIVENCHI',
  'Mft. Date': '31-01-2021',
  'Qty': 8000,
  'Price': 210,
  'Discount': 30},
 '11602265': {'Name': 'ARMANI',
  'Mft. Date': '03-02-2021',
  'Qty': 7500,
  'Price': 200,
  'Discount': 25},
 '11602266': {'Name': 'FENDI',
  'Mft. Date': '05-02-2021',
  'Qty': 7000,
  'Price': 190,
  'Discount': 20},
 '11602267': {'Name': 'CHANEL',
  'Mft. Date': '07-02-2021',
  'Qty': 6500,
  'Price': 180,
  'Discount': 15},
 '11602268': {'Name': 'RALPH LAUREN',
  'Mft. Date': '09-02-2021',
  'Qty': 6000,
  'Price': 170,
  'Discount': 10},
 '11602269': {'Name': 'HUGO BOSS',
  'Mft. Date': '11-02-2021',
  'Qty': 5500,
  'Price': 160,
  'Discount': 50},
 '11602270': {'Name': 'HERMES',
  'Mft. Date': '13-02-2021',
  'Qty': 5000,
  'Price': 160,
  'Discount': 45},
 '11602271': {'Name': 'YVES SAINT LAURENT',
  'Mft. Date': '15-02-2021',
  'Qty': 4500,
  'Price': 160,
  'Discount': 40},
 '11602272': {'Name': 'DIOR',
  'Mft. Date': '17-02-2021',
  'Qty': 4000,
  'Price': 150,
  'Discount': 35},
 '11602273': {'Name': 'VALENTINO',
  'Mft. Date': '19-02-2021',
  'Qty': 3500,
  'Price': 140,
  'Discount': 30},
 '11602274': {'Name': 'SALVATORE FERRAGAMO',
  'Mft. Date': '21-02-2021',
  'Qty': 3000,
  'Price': 130,
  'Discount': 25},
 '11602275': {'Name': 'DOLCE & GABBANA',
  'Mft. Date': '23-02-2021',
  'Qty': 2500,
  'Price': 120,
  'Discount': 20},
 '11602276': {'Name': 'MARC JACOBS',
  'Mft. Date': '25-02-2021',
  'Qty': 2000,
  'Price': 110,
  'Discount': 15},
 '11602277': {'Name': 'GUESS',
  'Mft. Date': '27-02-2021',
  'Qty': 1500,
  'Price': 100,
  'Discount': 10},
 '11602278': {'Name': 'ABERCROMBIE & FITCH',
  'Mft. Date': '29-02-2021',
  'Qty': 1000,
  'Price': 90,
  'Discount': 50},
 '11602279': {'Name': 'TED BAKER',
  'Mft. Date': '31-02-2021',
  'Qty': 900,
  'Price': 80,
  'Discount': 45},
 '11602280': {'Name': 'CHRISTIAN LOUBOUTIN',
  'Mft. Date': '3-03-2021',
  'Qty': 800,
  'Price': 70,
  'Discount': 40},
 '11602281': {'Name': 'CHLOE',
  'Mft. Date': '05-03-2021',
  'Qty': 700,
  'Price': 60,
  'Discount': 35},
 '11602282': {'Name': 'ALEXANDER MCQUEEN',
  'Mft. Date': '07-03-2021',
  'Qty': 600,
  'Price': 50,
  'Discount': 30},
 '11602283': {'Name': 'BURBERRY',
  'Mft. Date': '09-03-2021',
  'Qty': 500,
  'Price': 40,
  'Discount': 25},
 '11602284': {'Name': 'COACH',
  'Mft. Date': '11-03-2021',
  'Qty': 400,
  'Price': 30,
  'Discount': 20},
 '11602285': {'Name': 'COBB',
  'Mft. Date': '13-03-2021',
  'Qty': 300,
  'Price': 20,
  'Discount': 15},
 '11602286': {'Name': 'LOUIS PHILLIPE',
  'Mft. Date': '15-03-2021',
  'Qty': 200,
  'Price': 18,
  'Discount': 10},
 '11602287': {'Name': 'ALLEN SOLLY',
  'Mft. Date': '17-03-2021',
  'Qty': 190,
  'Price': 16,
  'Discount': 50},
 '11602288': {'Name': 'NIKE',
  'Mft. Date': '19-03-2021',
  'Qty': 180,
  'Price': 15,
  'Discount': 45},
 '11602289': {'Name': 'ADIDAS',
  'Mft. Date': '21-03-2021',
  'Qty': 100,
  'Price': 10,
  'Discount': 40},
 '11602290': {'Name': 'LEVIS',
  'Mft. Date': '23-03-2021',
  'Qty': 90,
  'Price': 280,
  'Discount': 35},
 '11602291': {'Name': 'ZARA',
  'Mft. Date': '25-03-2021',
  'Qty': 80,
  'Price': 270,
  'Discount': 30}}

### Checking if the discount given as input is same as that of item price in the dictionary

In [28]:
id = input("Enter the id :")
disc = int(input("Enter the discount :"))
if id in record:
    if disc != record[id]['Discount']:
        disc_price = record[id]['Discount'] + disc
    else:
        disc_price = record[id]['Discount']
else:
    print("Invalid input")

Enter the id :11602260
Enter the discount :30

### Updating the value of discount to dictionary

In [29]:
record[id]['Discount'] = disc_price

### Printing the dictionary with the updated value of discount

In [30]:
record

{'11602260': {'Name': 'LOUIS VUITTON',
  'Mft. Date': '23-01-2021',
  'Qty': 10000,
  'Price': 260,
  'Discount': 80},
 '11602261': {'Name': 'GUCCI',
  'Mft. Date': '25-01-2021',
  'Qty': 9500,
  'Price': 240,
  'Discount': 45},
 '11602262': {'Name': 'VERSACE',
  'Mft. Date': '27-01-2021',
  'Qty': 9000,
  'Price': 230,
  'Discount': 40},
 '11602263': {'Name': 'PRADA',
  'Mft. Date': '29-01-2021',
  'Qty': 8500,
  'Price': 220,
  'Discount': 35},
 '11602264': {'Name': 'GIVENCHI',
  'Mft. Date': '31-01-2021',
  'Qty': 8000,
  'Price': 210,
  'Discount': 30},
 '11602265': {'Name': 'ARMANI',
  'Mft. Date': '03-02-2021',
  'Qty': 7500,
  'Price': 200,
  'Discount': 25},
 '11602266': {'Name': 'FENDI',
  'Mft. Date': '05-02-2021',
  'Qty': 7000,
  'Price': 190,
  'Discount': 20},
 '11602267': {'Name': 'CHANEL',
  'Mft. Date': '07-02-2021',
  'Qty': 6500,
  'Price': 180,
  'Discount': 15},
 '11602268': {'Name': 'RALPH LAUREN',
  'Mft. Date': '09-02-2021',
  'Qty': 6000,
  'Price': 170,
  'Discount': 10},
 '11602269': {'Name': 'HUGO BOSS',
  'Mft. Date': '11-02-2021',
  'Qty': 5500,
  'Price': 160,
  'Discount': 50},
 '11602270': {'Name': 'HERMES',
  'Mft. Date': '13-02-2021',
  'Qty': 5000,
  'Price': 160,
  'Discount': 45},
 '11602271': {'Name': 'YVES SAINT LAURENT',
  'Mft. Date': '15-02-2021',
  'Qty': 4500,
  'Price': 160,
  'Discount': 40},
 '11602272': {'Name': 'DIOR',
  'Mft. Date': '17-02-2021',
  'Qty': 4000,
  'Price': 150,
  'Discount': 35},
 '11602273': {'Name': 'VALENTINO',
  'Mft. Date': '19-02-2021',
  'Qty': 3500,
  'Price': 140,
  'Discount': 30},
 '11602274': {'Name': 'SALVATORE FERRAGAMO',
  'Mft. Date': '21-02-2021',
  'Qty': 3000,
  'Price': 130,
  'Discount': 25},
 '11602275': {'Name': 'DOLCE & GABBANA',
  'Mft. Date': '23-02-2021',
  'Qty': 2500,
  'Price': 120,
  'Discount': 20},
 '11602276': {'Name': 'MARC JACOBS',
  'Mft. Date': '25-02-2021',
  'Qty': 2000,
  'Price': 110,
  'Discount': 15},
 '11602277': {'Name': 'GUESS',
  'Mft. Date': '27-02-2021',
  'Qty': 1500,
  'Price': 100,
  'Discount': 10},
 '11602278': {'Name': 'ABERCROMBIE & FITCH',
  'Mft. Date': '29-02-2021',
  'Qty': 1000,
  'Price': 90,
  'Discount': 50},
 '11602279': {'Name': 'TED BAKER',
  'Mft. Date': '31-02-2021',
  'Qty': 900,
  'Price': 80,
  'Discount': 45},
 '11602280': {'Name': 'CHRISTIAN LOUBOUTIN',
  'Mft. Date': '3-03-2021',
  'Qty': 800,
  'Price': 70,
  'Discount': 40},
 '11602281': {'Name': 'CHLOE',
  'Mft. Date': '05-03-2021',
  'Qty': 700,
  'Price': 60,
  'Discount': 35},
 '11602282': {'Name': 'ALEXANDER MCQUEEN',
  'Mft. Date': '07-03-2021',
  'Qty': 600,
  'Price': 50,
  'Discount': 30},
 '11602283': {'Name': 'BURBERRY',
  'Mft. Date': '09-03-2021',
  'Qty': 500,
  'Price': 40,
  'Discount': 25},
 '11602284': {'Name': 'COACH',
  'Mft. Date': '11-03-2021',
  'Qty': 400,
  'Price': 30,
  'Discount': 20},
 '11602285': {'Name': 'COBB',
  'Mft. Date': '13-03-2021',
  'Qty': 300,
  'Price': 20,
  'Discount': 15},
 '11602286': {'Name': 'LOUIS PHILLIPE',
  'Mft. Date': '15-03-2021',
  'Qty': 200,
  'Price': 18,
  'Discount': 10},
 '11602287': {'Name': 'ALLEN SOLLY',
  'Mft. Date': '17-03-2021',
  'Qty': 190,
  'Price': 16,
  'Discount': 50},
 '11602288': {'Name': 'NIKE',
  'Mft. Date': '19-03-2021',
  'Qty': 180,
  'Price': 15,
  'Discount': 45},
 '11602289': {'Name': 'ADIDAS',
  'Mft. Date': '21-03-2021',
  'Qty': 100,
  'Price': 10,
  'Discount': 40},
 '11602290': {'Name': 'LEVIS',
  'Mft. Date': '23-03-2021',
  'Qty': 90,
  'Price': 280,
  'Discount': 35},
 '11602291': {'Name': 'ZARA',
  'Mft. Date': '25-03-2021',
  'Qty': 80,
  'Price': 270,
  'Discount': 30}}

### Updating the inventory

In [31]:
js = json.dumps(record)
fd = open("record.json","w")
fd.write(js)
fd.close()